<?php

include_once('dc_2011_mobile.features.inc');

function dc_2011_mobile_views_post_render (&$view){
  if ($view->name == 'cod_schedule_mobile'){
    $rendered_fields = $view->style_plugin->rendered_fields;
    $titles = array();
    foreach ($rendered_fields as $key => $field){
      if(strtolower($field['type']) == 'schedule item'){
        if (in_array($field['title'], $titles)){
          unset($rendered_fields[$key]);
        }
        else{
          $titles[] = $field['title'];
        }
      }
    }
    $view->style_plugin->rendered_fields = $rendered_fields;
    dsm($view);
  }
}
