<?php

/**
 * @file
 * Provides extra condition where user can find if its on node page. Supports also content
 * translations.
 */

/**
 * Implementation of hook_init().
 */
function cep_node_init() {
  $item = menu_get_item();
  if ($item['path'] == 'node/%' && $plugin = context_get_plugin('condition', 'cep_node')) {
    $plugin->execute($item);
  }
}

/**
 * Implementation of hook_context_registry().
 */
function cep_node_context_registry() {
  return array(
    'conditions' => array(
      'cep_node' => array(
        'title' => t('Node ID'),
        'plugin' => 'cep_node_context_condition',
      ),
    ),
  );
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function cep_node_ctools_plugin_api($module, $api) {
  if ($module == 'context' && $api == 'plugins') {
    return array('version' => 3);
  }
}

/**
 * Implementation of hook_context_plugins().
 */
function cep_node_context_plugins() {
  $plugins = array();
  $plugins['cep_node_context_condition'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'cep_node') .'/plugins',
      'file' => 'cep_node_context_condition.inc',
      'class' => 'cep_node_context_condition',
      'parent' => 'context_condition',
    ),
  );
  return $plugins;
}